from tilings.strategies.batch import (all_cell_insertions, all_col_insertions,
                                      all_factor_insertions,
                                      all_placements,
                                      all_point_insertions,
                                      all_requirement_extensions,
                                      all_requirement_insertions,
                                      all_row_insertions, col_placements,
                                      partial_col_placements,
                                      partial_row_and_col_placements,
                                      partial_row_placements,
                                      requirement_corroboration,
                                      root_requirement_insertion,
                                      row_and_col_placements, row_placements)
